spring:

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      #enabled: false
      enabled: true

  jpa:
    generate-ddl: false
    #generate-ddl: true

    hibernate:
      ddl-auto: none
      #ddl-auto: create-drop

    # Показываем запросы
    show-sql: true

  spring-doc:
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml